export interface Account {
  customerCod: string,
  cityCode: string,
  cityName: string,
  countryCode: string,
  countryName: string,
  stateCode: string,
  stateName: string,
  businessSiteID: string,
  rank: string,
  aliasCode: string,
  businessName: string
  businessID: number,
  activeStatus: string,
  businessLocationID: number,
  divisionID: string,
  department: string
  // postalCode1: 547,
  // postalCode2: 29,
  // postalCode3: 1443,
  // businessClass: CUSTOMER,
  // effectiveDate: 1/14/2016 9:47,
  // endDate: 12/31/2099 23:59,
  // dUNNumber: 994882816,
  // dUNNumberExtension: 0,
  // hazardiousMaterialFlag: ,
  // hazardiousWasteMaterialFlag: ,
  // approvalState: APPROVED,
  // permanentBusinessSiteID: 0,
  // creditStatus: ,
  // billOnLandingRequired: ,
  // driverLoadingRequired: ,
  // driverUnLoadingRequired: ,
  // driverUnloadingCountrequired: ,
  // outsourcingFlag: ,
  // creditLimit: 10000,
  // creditBalance: 0,
  // brokerLoadFlag: N,
  // svcFlag: N,
  // lastContactDate: 1/14/2016 9:47,
  // approvalUser: JBRO850,
  // approvalDate: 1/14/2016 9:47,
  // rescheduleIfAppointmentChanges: N,
  // setIntervalforAppointment: ,
  // hazardiousMaterialExpdate: ,
  // authorizeJBHtoShipHazardiousmaterial: ,
  // hazardiousAutherizationdate: ,
  // addressID: 3593980

}
